In [18]:
import numpy as np

# Matrix Basics

In [12]:
all_zero = np.zeros((3,2))
cloned_zero = all_zero.copy()
print(f"all zero ({all_zero.shape}):\n{all_zero}\n cloned zero ({cloned_zero.shape}):\n{cloned_zero}")

all zero ((3, 2)):
[[0. 0.]
 [0. 0.]
 [0. 0.]]
 cloned zero ((3, 2)):
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [16]:
all_one = np.ones((2,3))
print(f"all one ({all_one.shape}):\n{all_one}")

all one ((2, 3)):
[[1. 1. 1.]
 [1. 1. 1.]]


In [17]:
increasing = np.arange(10)
print(f"increasing ({increasing.shape}):\n{increasing}")

increasing ((10,)):
[0 1 2 3 4 5 6 7 8 9]


In [15]:
diag = np.eye(5)
print(f"diagnal ({diag.shape}):\n{diag}")

diagnal ((5, 5)):
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


# Numerical Operations

In [22]:
a = np.array([
    [1,2],
    [3,1]
])

b= np.array([
    [1,2],
    [3,1]
])

sum = a + b
dif = a - b
mul = a * b
div = a / b
pow = a ** 2
sqr = np.sqrt(a)

print(f"a:\n{a}\nb:\n{b}\nsum:\n{sum}\ndif:\n{dif}\nmul:\n{mul}\ndiv:\n{div}\npow:\n{pow}\nsqr:\n{sqr}\n")

a:
[[1 2]
 [3 1]]
b:
[[1 2]
 [3 1]]
sum:
[[2 4]
 [6 2]]
dif:
[[0 0]
 [0 0]]
mul:
[[1 4]
 [9 1]]
div:
[[1. 1.]
 [1. 1.]]
pow:
[[1 4]
 [9 1]]
sqr:
[[1.         1.41421356]
 [1.73205081 1.        ]]



In [25]:
i = np.exp(a)
print(f"e's power:\n{i}")

e's power:
[[ 2.71828183  7.3890561 ]
 [20.08553692  2.71828183]]


# Matrix Operations

## Matrix Multiplication

In [28]:
mat_mul_1 = a @ b
mat_mul_2 = np.matmul(a,b)
print(f"Original Matrices:\n{a}\n{b}\nMatrix Multiplication\n Using '@':\n{mat_mul_1}\n Using np:\n{mat_mul_2}\n")

Original Matrices:
[[1 2]
 [3 1]]
[[1 2]
 [3 1]]
Matrix Multiplication
 Using '@':
[[7 4]
 [6 7]]
 Using np:
[[7 4]
 [6 7]]



## Matrix Transpose

In [32]:
# Randomize a 5-d matrix
rand = np.random.randn(2, 3, 4, 5, 6)
rand_transposed = rand.transpose(3, 0, 1, 4, 2)

print(f"Random Matrix:\n{rand}\nTransposed Matrix:\n{rand_transposed}")

Random Matrix:
[[[[[-1.48519685e+00 -8.01602506e-01  7.86905963e-01 -7.00439768e-01
     -1.50484757e-01  2.16454758e-01]
    [-7.99319747e-01  2.10590807e+00  1.50046480e+00 -1.45723704e-01
      5.41223226e-01  9.96047289e-02]
    [ 1.38630184e+00  1.15908154e+00  7.99177043e-01 -2.66072102e+00
     -8.74596169e-01 -1.77663775e+00]
    [ 1.01173052e+00 -3.74406219e-01 -1.06932227e+00  6.05413918e-01
     -1.20740280e+00  2.27875244e+00]
    [-7.09514575e-01 -8.07084205e-01 -8.53873232e-01 -2.96058489e+00
     -1.64126539e-01 -8.07562630e-01]]

   [[ 1.34322417e+00 -6.76405461e-01 -8.43225554e-01  3.89670001e-02
      1.00962985e-01 -5.56191298e-01]
    [ 8.84841004e-02  4.56210015e-01 -1.57871962e+00 -5.89787233e-02
      4.12378648e-02 -5.43065564e-01]
    [-2.19712548e-01 -1.92968593e-01  1.32817280e-01 -3.06820226e-01
      9.76336996e-01 -4.51213933e-01]
    [ 9.42160357e-01  8.03392023e-01 -8.34422072e-01 -1.00251766e-01
     -1.05428531e+00 -1.47506621e+00]
    [ 3.88431529e-01

## Matrix Reshape

In [36]:
# Reshaping
before = np.arange(20)
after = before.reshape(4,5)
print(f"Before:\n{before}\nAfter:\n{after}\n")

Before:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
After:
[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]



# Matrix Index

In [44]:
m0 = np.arange(5)
m1 = np.ones_like(m0)
m2 = np.concatenate([m0, m1], axis=0)
m3 = np.stack([m0, m1], axis=0)
m4 = np.stack([m0, m1, m0], axis=1)

print(f"m0:\n{m0}\nm1:\n{m1}\nm2:\n{m2}\nm3:\n{m3}\nm4:\n{m4}\n")

m0:
[0 1 2 3 4]
m1:
[1 1 1 1 1]
m2:
[0 1 2 3 4 1 1 1 1 1]
m3:
[[0 1 2 3 4]
 [1 1 1 1 1]]
m4:
[[0 1 0]
 [1 1 1]
 [2 1 2]
 [3 1 3]
 [4 1 4]]



## Shape Broadcasting

In [45]:
# Success
before = np.arange(10)
after = before + 10
print(f"Before:\n{before}\nAfter:\n{after}\n")

Before:
[0 1 2 3 4 5 6 7 8 9]
After:
[10 11 12 13 14 15 16 17 18 19]



In [47]:
# Unexpected
m0 = np.arange(5).reshape(1,5)
m1 = np.arange(5).reshape(5,1)
sum = m0 + m1
print(f"\nm0:\n{m0}\nm1:\n{m1}\nsum:\n{sum}\n")


m0:
[[0 1 2 3 4]]
m1:
[[0]
 [1]
 [2]
 [3]
 [4]]
sum:
[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]

