In [1]:
import torch

# Put Tensors/Models on GPU

## On CPU
Put a matrix on cpu.

In [3]:
mat_cpu = torch.zeros([3,3])
print(f"Matrix:\n{mat_cpu}\nDevice:\n{mat_cpu.device}")

Matrix:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
Device:
cpu


## Directly on GPU

In [5]:
mat_gpu = torch.zeros([3,3], device='cuda')
print(f"Matrix:\n{mat_gpu}\nDevice:\n{mat_gpu.device}")

Matrix:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], device='cuda:0')
Device:
cuda:0


## Move from CPU to GPU

In [9]:
mat_cpu_to_gpu = mat_cpu.to('cuda')
print(f"Matrix:\n{mat_cpu_to_gpu}\nDevice:\n{mat_cpu_to_gpu.device}")

Matrix:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], device='cuda:0')
Device:
cuda:0


# Move a model to GPU

In [11]:
import torch
class TinyModel(torch.nn.Module):
    def __init__(self):
        super(TinyModel, self).__init__()
        self.linear1 = torch.nn.Linear(100,200)
        self.activation = torch.nn.ReLU()
        self.linear2 = torch.nn.Linear(200,10)
        self.softmax = torch.nn.Softmax()

    def forward(self, x):
        x = self.linear1(x)
        x = self.activation(x)
        x = self.linear2(x)
        x = self.softmax(x)
        return x

tinymodel = TinyModel().to('cuda')

# Move GPU tensor back to numpy

In [15]:
tensor_gpu = torch.zeros([3,3], device='cuda')
back_to_cpu = tensor_gpu.detach().cpu().numpy()
print(f"GPU:\n{tensor_gpu}\nDevice:{tensor_gpu.device}\n\nCPU:\n{back_to_cpu}")

GPU:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], device='cuda:0')
Device:cuda:0

CPU:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
